export enum ImageType {
    EXPERICENCE='EXPERICENCE',
    PROJECT='PROJECT',
    ACHIEVEMENT='ACHIEVEMENT',
    PORTFOLIO='PORTFOLIO',
    USER='USER',
  }
export enum DataType {
  EXPERICENCE='EXPERICENCE',
  PROJECT='PROJECT',
  ACHIEVEMENT='ACHIEVEMENT',
  PORTFOLIO_CONTENT='PORTFOLIO_CONTENT',
  PORTFOLIO_IMAGE='PORTFOLIO_IMAGE',
  PORTFOLIO_DATA='PORTFOLIO_DATA',
  USER='USER',
}